package com.untildawn.Enums;

public enum Menus {
    LOGIN_MENU,
    SIGNUP_MENU,
    MAIN_MENU,
    PREGAME_MENU,
    PROFILE_MENU,
    AVATAR_MENU,
    GRAPHICS_AUDIO_SETTING_MENU,
    KEYBOARD_SETTING_MENU,
    SCOREBOARD_MENU,
    HINT_MENU,
    RESUME_LAST_GAME_MENU,
    LOGOUT_MENU,
    ;

}
